[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "NRVQA"
version = "1.0.0"
description = "Library for PIQE"
dependencies = []


py-modules = ["piqe"]
